version: '3.3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: banco_engenharia
      MYSQL_USER: aluno
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
